apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: APP_NAME
  name: APP_NAME
  namespace: gravity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: APP_NAME
  strategy: {}
  template:
    metadata:
      labels:
        app: APP_NAME
    spec:
      containers:
        - image: rjgc2810/kubernetes-devops-security:GIT_COMMIT
          name: APP_NAME-container
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: APP_NAME
  name: APP_NAME-svc
  namespace: gravity
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: APP_NAME
  type: NodePort
